# Generated by Django 5.0.7 on 2024-07-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faq_news_image_service_image_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='news/')),
            ],
        ),
        migrations.RenameField(
            model_name='newsimage',
            old_name='tour',
            new_name='news',
        ),
    ]
